### PR TITLE
Full Math support & small changes

### PR DESCRIPTION
**Pull request by Saiv46**

### CODE REVIEW

**Comment by Saiv46** [comment]
> [CLA assistant check](https://cla-assistant.io/NectarJS/nectarjs?pullRequest=94)
> All committers have signed the CLA.

The feeling like I signed a contract with the devil.

**Comment by adrien-thierry** [comment]
Thank you very much for your contribution !

**Comment by Saiv46** [comment]
Umm, this pull request is still open.

**Comment by adrien-thierry** [comment]
It looks closed here

**Pull request merged**
